<?php 
	$_lang = array(
		'Current Site'=>'当前站点',
		'Change Site'=>'更改站点',
		'Chinese'=>'English',
		'Home'=>'主页',
		'Quick Search'=>'快速搜索',
		'Buildability'=>'制造能力',
		'Spec'=>'客户规范',
		'InPlan'=>'InPlan资料',
		'Genesis'=>'CAM资料',
		'Home Navigate'=>'主页导航',
		'Search or double click an item to view details' =>'输入关键词搜索或双击一条查看详细资料',
		'Job Attributes'=>'料号基本资料',
		'Data Navigate'=>'资料导航',
		'Job History'=>'料号更改历史',
		'Drawing'=>'图纸',
		'Upload'=>'上传',
		'Download'=>'下载',
        'Delete'=>'删除',
        'Approve'=>'审批',
		'Obsolete'=>'荒废',
		'Please Refer'=>'请参考',
		'Stackup'=>'压板叠构',
		'Drill Table'=>'钻孔表',
		'Traveller Routing'=>'工单流程',
		'Cam Instruction'=>'CAM制作指示',
		'Job Information'=>'基本资料',
		'Job Name'=>'料号名称',
		'Board Type'=>'板 类 型',
		'Mrp Name'=>'成品型号',
		'Layer Count'=>'层&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp数',
		'Customer'=>'客户名称',
		'End Customer'=>'终端客户',
		'Customer P/N'=>'客户编号',
		'Customer Rev'=>'客户版本',
		'Operator'=>'MI 制 作 者',
		'Deliverable Type'=>'交货形式',
		'UL Type'=>'UL 类 型',
		'PCB Size X'=>'单元尺寸 X',
		'PCB Size Y'=>'单元尺寸 Y',
		'PNL Size X'=>'PNL 尺寸 X',
		'PNL Size Y'=>'PNL 尺寸 Y',
		'Sheet Size X'=>'大料尺寸 X',
		'Sheet Size Y'=>'大料尺寸 Y',
		'Num PCBs In PNL'=>'Panel中Unit数',
		'Num Arrays In PNL'=>'Panel中的Array数',
		'Num PCBs In Array'=>'Array中的Unit数',
		'Num Panels In Sheet'=>'Sheet中的Panel数',
		'Panel Design'=>'Panel数据',
		'Finish'=>'表面处理',
		'Surface Finish'=>'表面处理',
		'Solder Mask Type'=>'绿油型号',
		'Solder Mask Color'=>'绿油颜色',
		'2nd Solder Mask Type'=>'二次绿油型号',
		'2nd Solder Mask Color'=>'二次绿油颜色',
		'Legend Type'=>'印字型号',
		'ECN History'=>'ECN 历史',
		'TQ'=>'工程问题',
		'Order Status'=>'订单类型',
		'Mfg Class'=>'制作等级',
		'A/W Rev'=>'A/W版本',
		'B/P Rev'=>'B/P版本',
		'Stackup Info'=>'压板信息',
		'Board Thickness'=>'客户要求板厚',
		'Tol ( + )'=>'公差 ( + )',
		'Tol ( - )'=>'公差 ( - )',
		'Calc Method'=>'厚度计算方法',
		'Mtl Vendor'=>'物料厂商',
		'Mtl Family'=>'物料类型',
		'Ink Type'=>'油墨类型',
		'Legend Color'=>'文字颜色',
		'Peelable Mask Req'=>'蓝胶要求',
		'Peelable Mask Application'=>'蓝胶位置',
		'Peelable Mask Material Type'=>'蓝胶物料类型',
		'Peelable Mask Type'=>'蓝胶类型',
		'Min Surface Finish Thk'=>'最小表面处理厚度',
		'Selective Plate'=>'选择性表面处理',
		'Min Selective Plate Thk'=>'最小选择性表面处理厚',
		'Plated Tips Required'=>'金手指要求',
		'Tip Style'=>'金手指类别',
		'Tip Type'=>'金手指类型',
		'Min Gold Tip Thickness'=>'金手指最小金厚',
		'Layer Parameters'=>'各层参数',
		'Layer Index'=>'层名',
		'LW Min (mil)'=>'最小线宽',
		'SP Min (mil)'=>'最小线距',
		'AR Min (mil)'=>'最小锡圈',
		'Tool Table'=>'工具表',
		'Sheet Cutting'=>'开料图',
		'Left click to view big picture'=>'点击查看大图',
		'Read Me'=>'备注信息',
		'Date'=>'修改时间',
		'PT'=>'MI制作者',
		'Job Creation Date'=>'料号创建日期',
		'Job Approval Date'=>'料号出单日期',
		'Customer Thickness'=>'客户要求板厚度',
		'Pressed Thickness'=>'压板厚度控制范围',
		'Design Thickness'=>'设计压板厚度',
		'E-Spray Coating'=>'噴塗油墨',
		'2nd E-Spray Coating'=>'二次噴塗',
		'E-Spray Coating Color'=>'噴塗油墨颜色',
		'2nd E-Spray Coating Color'=>'二次噴塗油墨颜色',
		'Processing, please wait ...'=>'数据加载中，请稍等...',

		
	);
	function getLang($text,$en){
		global $_lang;
		$which_lang = $text;
		if ($en == 'zh-cn') {
			if ($_lang[$text]) $which_lang = $_lang[$text];
		}
		return $which_lang ;
	}
?>