SELECT pv.PART_NUMBER,
		 "DRILL_PROGRAM"."DRILL_PROGRAM",
		 f_get_min_drill_by_program("PV"."PART_NUMBER", "PV"."DRILL_VERSION_VERSION", "DRILL_PROGRAM"."DRILL_PROGRAM", 'Y') Min_drill_by_program
FROM 	NC_PROGRAM,
		DRILL_PROGRAM,
		part_version pv
WHERE pv.PART_NUMBER = '@@part_number@@'        
AND   pv.version = f_get_part_version2(pv.PART_NUMBER,10)
AND   "DRILL_PROGRAM"."PART_NUMBER" (+) = pv.PART_NUMBER
AND   "DRILL_PROGRAM"."DRILL_PROGRAM_VERSION_VERSION" (+) = pv.DRILL_PROGRAM_VERSION_VERSION
AND	"NC_PROGRAM"."PROCESS_TYPE" (+) = 'D'
AND   "NC_PROGRAM"."PROGRAM" (+) = "DRILL_PROGRAM"."DRILL_PROGRAM"
ORDER BY pv.PART_NUMBER,
		 "DRILL_PROGRAM"."DRILL_PROGRAM"
